[tools]
swiftformat = "latest"
node = "22"
tuist = "4.200.2"

[settings]
jobs = 6
http_timeout = "30s"
experimental = true

[tasks.format]
run = "swiftformat ."
description = "Format project"
alias = "f"
